# Generated by Django 5.0 on 2023-12-22 19:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_phone_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст')),
                ('image', models.ImageField(upload_to='contact', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Заказать обратный Звонок',
                'verbose_name_plural': 'Заказать обратный Звонок',
            },
        ),
    ]
