# Generated by Django 5.0 on 2023-12-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
    ]
