# Generated by Django 5.0 on 2023-12-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_consent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
