# Generated by Django 5.0 on 2023-12-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='title',
            new_name='name',
        ),
    ]
