# Generated by Django 5.0 on 2023-12-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_rename_title_messages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Тел.ном')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка на Просмотр',
                'verbose_name_plural': 'Заявки на Просмотры',
            },
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Заявка на Вопрос', 'verbose_name_plural': 'Заявки на Вопросы'},
        ),
    ]
