# Generated by Django 5.0 on 2023-12-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_rooms_apartment_exploitation_apartment_floor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Добавить Квартиру', 'verbose_name_plural': 'Добавить Квартиру'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Добавить Комнаты', 'verbose_name_plural': 'Добавить Комнаты'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='razmer',
            field=models.CharField(default=1, max_length=255, verbose_name='Размер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='layout_text',
            field=models.CharField(max_length=255, verbose_name='Тип планировок '),
        ),
        migrations.CreateModel(
            name='ApartmentOsob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choise_image', to='apartment.apartment')),
            ],
            options={
                'verbose_name': 'Добавить Особенности',
                'verbose_name_plural': 'Добавить Особенности',
                'unique_together': {('settings', 'title')},
            },
        ),
    ]
