# Generated by Django 5.0 on 2023-12-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_apartment_options_alter_rooms_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Статус квартиры')),
            ],
            options={
                'verbose_name': 'Добавить Статус',
                'verbose_name_plural': 'Добавить Статус',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус квартиры'),
        ),
    ]
