# Generated by Django 5.0 on 2023-12-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_savedfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedFilter',
        ),
    ]
