# Generated by Django 5.0 on 2023-12-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_delete_savedfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(verbose_name='Номер этажа')),
            ],
            options={
                'verbose_name': 'Добавить Этажи',
                'verbose_name_plural': 'Добавить Этажи',
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor_min', models.IntegerField(blank=True, null=True)),
                ('floor_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Настройка фильтрации ',
                'verbose_name_plural': 'Настройка фильтрации ',
            },
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Этажи'),
        ),
    ]
