# Generated by Django 5.0 on 2023-12-28 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_floor_savedfilter_alter_apartment_floor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedFilter',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_form', to='apartment.floor'),
        ),
    ]
