# Generated by Django 5.0 on 2023-12-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_alter_apartment_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='title',
            field=models.CharField(max_length=2, verbose_name='Номер этажа'),
        ),
    ]
