# Generated by Django 5.0 on 2023-12-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_alter_floor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сколько комнат в числовам формате'),
        ),
    ]
