# Generated by Django 5.0 on 2023-12-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_rename_number_rooms_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='floor',
        ),
    ]
