# Generated by Django 5.0 on 2023-12-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0015_remove_rooms_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='title',
            new_name='room',
        ),
    ]
