# Generated by Django 5.0 on 2023-12-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0016_rename_title_apartment_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.rooms'),
        ),
    ]
