# Generated by Django 5.0 on 2023-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0020_alter_block_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='title',
        ),
        migrations.AddField(
            model_name='block',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Название блока'),
        ),
    ]
