# Generated by Django 5.0 on 2023-12-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_remove_block_title_block_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='it',
            field=models.IntegerField(default=1, verbose_name='Id'),
            preserve_default=False,
        ),
    ]
