# Generated by Django 5.0 on 2023-12-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0022_status_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
    ]
