# Generated by Django 5.0 on 2024-01-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0024_block_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
