# Generated by Django 5.0 on 2024-01-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0025_alter_apartment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='razmer',
            field=models.FloatField(verbose_name='Введите размер'),
        ),
    ]
