# Generated by Django 5.0 on 2023-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0026_block_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='it',
            field=models.IntegerField(default=None, verbose_name='Нумерация'),
        ),
    ]
