# Generated by Django 5.0 on 2023-12-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0027_alter_block_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='it',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нумерация'),
        ),
    ]
