# Generated by Django 5.0 on 2024-01-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0028_rename_title_floor_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='number',
            new_name='title',
        ),
    ]
