# Generated by Django 5.0 on 2024-01-03 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0029_rename_number_floor_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название особенности')),
            ],
            options={
                'verbose_name': 'Добавить особенность',
                'verbose_name_plural': 'Добавить особенности',
            },
        ),
        migrations.AlterField(
            model_name='apartmentosob',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.osob'),
        ),
    ]
