# Generated by Django 5.0 on 2024-01-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0031_alter_osob_options_alter_apartment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentosob',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartmentosob', to='apartment.apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentosob',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osob', to='apartment.osob'),
        ),
    ]
