# Generated by Django 5.0 on 2023-12-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_projects_delete_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=255, verbose_name='Первый заголовок')),
                ('first_subtitle', models.CharField(max_length=255, verbose_name='Первый подзаголовок')),
                ('first_descriptions', models.CharField(max_length=255, verbose_name='Первый описание')),
                ('second_title', models.CharField(max_length=255, verbose_name='Второй заголовок')),
                ('second_subtitle', models.CharField(max_length=255, verbose_name='Второй подзаголовок')),
                ('second_descriptions', models.CharField(max_length=255, verbose_name='Второй описание')),
                ('third_title', models.CharField(max_length=255, verbose_name='Третий заголовок')),
                ('third_subtitle', models.CharField(max_length=255, verbose_name='Третий подзаголовок')),
                ('third_descriptions', models.CharField(max_length=255, verbose_name='Третий описание')),
                ('four_title', models.CharField(max_length=255, verbose_name='Четвертый заголовок')),
                ('four_subtitle', models.CharField(max_length=255, verbose_name='Четвертый подзаголовок')),
                ('four_descriptions', models.CharField(max_length=255, verbose_name='Четвертый описание')),
                ('five_title', models.CharField(max_length=255, verbose_name='Пятый заголовок')),
                ('five_subtitle', models.CharField(max_length=255, verbose_name='Пятый подзаголовок')),
                ('five_descriptions', models.CharField(max_length=255, verbose_name='Пятый описание')),
                ('six_title', models.CharField(max_length=255, verbose_name='Шестой заголовок')),
                ('six_subtitle', models.CharField(max_length=255, verbose_name='Шестой подзаголовок')),
                ('six_descriptions', models.CharField(max_length=255, verbose_name='Шестой описание')),
            ],
            options={
                'verbose_name': 'Мы в числах',
                'verbose_name_plural': 'Мы в числах',
            },
        ),
    ]
