# Generated by Django 5.0 on 2023-12-22 00:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_rename_test_pride_first_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Euro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст')),
            ],
            options={
                'verbose_name': 'Что такое Европейский квартал',
                'verbose_name_plural': 'Что такое Европейский квартал',
            },
        ),
        migrations.AlterField(
            model_name='pride',
            name='first',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Первый Информационный текст'),
        ),
        migrations.AlterField(
            model_name='pride',
            name='five',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Пятый Информационный текст'),
        ),
        migrations.AlterField(
            model_name='pride',
            name='four',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Четвертый Информационный текст'),
        ),
        migrations.AlterField(
            model_name='pride',
            name='second',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Второй Информационный текст'),
        ),
        migrations.AlterField(
            model_name='pride',
            name='six',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Шестой Информационный текст'),
        ),
        migrations.AlterField(
            model_name='pride',
            name='third',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Третий Информационный текст'),
        ),
        migrations.CreateModel(
            name='EuroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='euro_image')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='euro_image', to='secondary.euro')),
            ],
            options={
                'unique_together': {('settings', 'image')},
            },
        ),
    ]
