# Generated by Django 5.0 on 2023-12-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_advantages_advantagestitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantages',
            options={'verbose_name': 'Преимущества номер один', 'verbose_name_plural': 'Преимущества номер один'},
        ),
    ]
