# Generated by Django 5.0 on 2023-12-22 18:05

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_alter_advantages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='Advantages/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='EnviromentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Описание')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='secondary.advantages')),
            ],
            options={
                'unique_together': {('settings', 'title', 'subtitle')},
            },
        ),
    ]
