# Generated by Django 5.0 on 2023-12-22 18:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_environment_enviromenttitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name': 'Окружение Европейского квартала', 'verbose_name_plural': 'Окружение Европейского квартала'},
        ),
        migrations.AlterField(
            model_name='enviromenttitle',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='secondary.environment'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
    ]
