# Generated by Django 5.0 on 2023-12-22 18:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0013_alter_enviromenttitle_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Заголовок')),
                ('subtitle', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улица',
            },
        ),
    ]
