# Generated by Django 5.0 on 2023-12-26 21:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0014_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choise',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
    ]
