# Generated by Django 5.0 on 2023-12-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0016_advantagestwo_advantagestwotitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantagestwo',
            options={'verbose_name': 'Преимущества номер два', 'verbose_name_plural': 'Преимущества номер два'},
        ),
    ]
