# Generated by Django 5.0 on 2023-12-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Логотип компании'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo_complex',
            field=models.ImageField(upload_to='logo/', verbose_name='Логотип комплекса'),
        ),
    ]
