# Generated by Django 5.0 on 2023-12-22 01:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='gallery/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo_complex',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Фотография'),
        ),
    ]
