# Generated by Django 5.0 on 2023-12-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_about_image_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.URLField(verbose_name='ссылка на карту из GoogleMaps')),
            ],
            options={
                'verbose_name': 'Google карта',
                'verbose_name_plural': 'Google карта',
            },
        ),
    ]
