# Generated by Django 5.0 on 2023-12-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_maps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maps',
        ),
    ]
