# Generated by Django 5.0 on 2023-12-26 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_gallery_title_alter_settings_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsphone',
            options={'verbose_name': 'Дополнительный телефонный номер', 'verbose_name_plural': 'Дополнительный телефонный номер'},
        ),
        migrations.CreateModel(
            name='SettingsOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_title', to='base.settings')),
            ],
            options={
                'verbose_name': 'Офис продаж',
                'verbose_name_plural': 'Офис продаж',
                'unique_together': {('settings', 'phone', 'location')},
            },
        ),
    ]
