# Generated by Django 5.0 on 2023-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_settingsphone_options_settingsoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoffice',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='График работы'),
        ),
    ]
