# Generated by Django 5.0 on 2023-12-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_settingsoffice_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Whatsapp номер'),
            preserve_default=False,
        ),
    ]
