# Generated by Django 5.0 on 2023-12-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_settings_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsSoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название соц.сети')),
                ('username', models.CharField(max_length=255, verbose_name='username аккаунта')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_soc', to='base.settings')),
            ],
            options={
                'verbose_name': 'Соц сети',
                'verbose_name_plural': 'Соц сети',
                'unique_together': {('settings', 'title')},
            },
        ),
    ]
