# Generated by Django 5.0 on 2023-12-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Страница контакты', 'verbose_name_plural': 'Страница контакты'},
        ),
    ]
